//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarID { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public int DayPrice { get; set; }
        public int LateDayPrice { get; set; }
        public Nullable<int> ProductionYear { get; set; }
        public string Gear { get; set; }
        public string Image { get; set; }
    
        public virtual CarDetail CarDetail { get; set; }
    }
}
